import type { 
  Campaign, Lead, MarketingSummary, FunnelStage, ChannelPerformance, LeadTrend, AudienceSegment 
} from '@/types/marketing';

// ─── Marketing Summary ───────────────────────────────────────────────────────
export const MOCK_MARKETING_SUMMARY: MarketingSummary = {
  totalCampaigns: 24,
  activeCampaigns: 8,
  totalLeads: 1250,
  totalConversions: 185,
  conversionRate: 14.8,
  totalBudget: 45000,
  totalSpend: 32400,
  costPerLead: 25.92,
  averageROI: 320,
  revenueAttributed: 154000,
};

// ─── Campaigns ───────────────────────────────────────────────────────────────
export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'c1',
    name: 'Summer Refresh 2026',
    channel: 'Email',
    status: 'Active',
    budget: 5000,
    spend: 3200,
    leads: 450,
    conversions: 62,
    roi: 450,
    startDate: '2026-02-01',
    endDate: '2026-03-15',
    targetAudience: 'Returning Customers',
    tags: ['seasonal', 'discount'],
    createdBy: 'Sarah Marketer',
  },
  {
    id: 'c2',
    name: 'Q1 Facebook Ads',
    channel: 'Ads',
    status: 'Active',
    budget: 8000,
    spend: 7200,
    leads: 320,
    conversions: 45,
    roi: 280,
    startDate: '2026-01-01',
    endDate: '2026-03-31',
    targetAudience: 'Small Business Owners',
    tags: ['paid', 'cold-outreach'],
    createdBy: 'Jason Growth',
  },
  {
    id: 'c3',
    name: 'Product Launch Webinar',
    channel: 'Social',
    status: 'Completed',
    budget: 2000,
    spend: 1850,
    leads: 180,
    conversions: 28,
    roi: 520,
    startDate: '2026-01-15',
    endDate: '2026-02-15',
    targetAudience: 'Tech early adopters',
    tags: ['event', 'webinar'],
    createdBy: 'Emily Content',
  },
  {
    id: 'c4',
    name: 'SMS Flash Sale',
    channel: 'SMS',
    status: 'Paused',
    budget: 1500,
    spend: 400,
    leads: 85,
    conversions: 12,
    roi: 150,
    startDate: '2026-02-20',
    endDate: '2026-02-22',
    targetAudience: 'Active VIPs',
    tags: ['sms', 'urgent'],
    createdBy: 'Sarah Marketer',
  },
  {
    id: 'c5',
    name: 'Referral program boost',
    channel: 'Referral',
    status: 'Active',
    budget: 3000,
    spend: 1200,
    leads: 95,
    conversions: 22,
    roi: 680,
    startDate: '2026-02-05',
    endDate: '2026-05-05',
    targetAudience: 'All Existing Customers',
    tags: ['organic', 'referral'],
    createdBy: 'Emily Content',
  },
  {
    id: 'c6',
    name: 'Winter Clearance',
    channel: 'Email',
    status: 'Completed',
    budget: 4000,
    spend: 3950,
    leads: 380,
    conversions: 48,
    roi: 360,
    startDate: '2025-12-01',
    endDate: '2026-01-10',
    targetAudience: 'Bargain Hunters',
    tags: ['seasonal', 'clearance'],
    createdBy: 'Sarah Marketer',
  },
];

// ─── Leads ──────────────────────────────────────────────────────────────────
export const MOCK_LEADS: Lead[] = [
  {
    id: 'l1',
    name: 'Michael Scott',
    email: 'm.scott@dundermifflin.com',
    phone: '+1 555-0123',
    company: 'Dunder Mifflin Scranton',
    source: 'Organic',
    status: 'Qualified',
    score: 85,
    assignedTo: 'Dwight Schrute',
    campaignName: 'Summer Refresh 2026',
    value: 5000,
    createdAt: '2026-02-15T10:00:00Z',
    location: 'Scranton, PA',
    tags: ['paper', 'high-intent'],
  },
  {
    id: 'l2',
    name: 'Leslie Knope',
    email: 'knope@pawnee.gov',
    phone: '+1 555-9876',
    company: 'Pawnee Parks & Rec',
    source: 'Paid Ads',
    status: 'Contacted',
    score: 64,
    assignedTo: 'Ron Swanson',
    campaignName: 'Q1 Facebook Ads',
    value: 12000,
    createdAt: '2026-02-18T14:30:00Z',
    location: 'Pawnee, IN',
    tags: ['government', 'enterprise'],
  },
  {
    id: 'l3',
    name: 'Harvey Specter',
    email: 'harvey@ps-ross.com',
    phone: '+1 555-4422',
    company: 'Pearson Specter',
    source: 'Referral',
    status: 'New',
    score: 92,
    assignedTo: 'Mike Ross',
    value: 25000,
    createdAt: '2026-02-27T09:15:00Z',
    location: 'New York, NY',
    tags: ['legal', 'vip'],
  },
  {
    id: 'l4',
    name: 'Walter White',
    email: 'heisenberg@gmail.com',
    phone: '+1 555-0001',
    company: 'A1A Car Wash',
    source: 'Social',
    status: 'Converted',
    score: 78,
    assignedTo: 'Jesse Pinkman',
    campaignName: 'Product Launch Webinar',
    value: 8500,
    createdAt: '2026-01-20T11:45:00Z',
    location: 'Albuquerque, NM',
    tags: ['manufacturing', 'risk'],
  },
  {
    id: 'l5',
    name: 'Don Draper',
    email: 'draper@scdp.com',
    phone: '+1 555-1111',
    company: 'Sterling Cooper',
    source: 'Direct',
    status: 'Lost',
    score: 45,
    assignedTo: 'Peggy Olson',
    value: 18000,
    createdAt: '2026-01-05T16:20:00Z',
    location: 'New York, NY',
    tags: ['advertising', 'old-school'],
  },
];

// ─── Analytics Data ──────────────────────────────────────────────────────────
export const MOCK_FUNNEL_DATA: FunnelStage[] = [
  { stage: 'Awareness', count: 5000, percent: 100, color: '#94a3b8' },
  { stage: 'Interest', count: 2450, percent: 49, color: '#6366f1' },
  { stage: 'Qualified', count: 1250, percent: 25, color: '#f59e0b' },
  { stage: 'Negotiation', count: 480, percent: 9.6, color: '#0ea5e9' },
  { stage: 'Converted', count: 185, percent: 3.7, color: '#10b981' },
];

export const MOCK_CHANNEL_PERFORMANCE: ChannelPerformance[] = [
  { channel: 'Email', leads: 420, conversions: 58, spend: 8500, roi: 420 },
  { channel: 'Facebook Ads', leads: 380, conversions: 42, spend: 12000, roi: 210 },
  { channel: 'Google Search', leads: 210, conversions: 35, spend: 15400, roi: 185 },
  { channel: 'LinkedIn', leads: 95, conversions: 18, spend: 6500, roi: 340 },
  { channel: 'Referral', leads: 85, conversions: 24, spend: 1200, roi: 780 },
  { channel: 'Direct', leads: 60, conversions: 8, spend: 0, roi: 1200 },
];

export const MOCK_LEAD_TREND: LeadTrend[] = [
  { month: 'Sep', leads: 450, conversions: 52, spend: 8000 },
  { month: 'Oct', leads: 520, conversions: 58, spend: 9500 },
  { month: 'Nov', leads: 680, conversions: 72, spend: 11000 },
  { month: 'Dec', leads: 850, conversions: 95, spend: 15000 },
  { month: 'Jan', leads: 920, conversions: 105, spend: 16500 },
  { month: 'Feb', leads: 1250, conversions: 185, spend: 32400 },
];

export const MOCK_AUDIENCE_SEGMENTS: AudienceSegment[] = [
  {
    id: 's1',
    name: 'High Value Customers',
    filters: ['Revenue > 10000', 'Last purchase < 90 days'],
    size: 245,
    createdAt: '2026-01-10',
    tags: ['vip', 'retention'],
  },
  {
    id: 's2',
    name: 'Inactive Leads',
    filters: ['Status = New', 'Age > 30 days'],
    size: 580,
    createdAt: '2026-01-15',
    tags: ['re-engagement'],
  },
  {
    id: 's3',
    name: 'Scranton Paper Prospect',
    filters: ['Location = Scranton', 'Tags contains paper'],
    size: 12,
    createdAt: '2026-02-20',
    tags: ['niche', 'geo'],
  },
];
