import { TimeEntry, Timesheet, ProjectTimeStats, AttendanceRecord, TimeSummary } from '@/types/time';

export const MOCK_TIME_ENTRIES: TimeEntry[] = [
  {
    id: 'TIME-001',
    projectId: 'PRJ-101',
    projectName: 'E-commerce Platform Redesign',
    taskId: 'TSK-001',
    taskName: 'UI Component Architecture',
    clientId: 'CLT-001',
    clientName: 'Global Retail Corp',
    employeeId: 'EMP-005',
    employeeName: 'Jeel Uniya',
    date: '2024-03-01',
    duration: 4.5,
    isBillable: true,
    billableRate: 150,
    notes: 'Developed core layout components and implemented shadcn/ui shared library.',
    status: 'Completed',
  },
  {
    id: 'TIME-002',
    projectId: 'PRJ-101',
    projectName: 'E-commerce Platform Redesign',
    taskId: 'TSK-002',
    taskName: 'API Integration - Checkout Flow',
    clientId: 'CLT-001',
    clientName: 'Global Retail Corp',
    employeeId: 'EMP-005',
    employeeName: 'Jeel Uniya',
    date: '2024-03-01',
    duration: 3.5,
    isBillable: true,
    billableRate: 150,
    notes: 'Connecting Stripe webhooks and managing order state in Redux.',
    status: 'Completed',
  },
  {
    id: 'TIME-003',
    projectId: 'PRJ-102',
    projectName: 'Mobile App Backend',
    taskId: 'TSK-105',
    taskName: 'Database Schema Migration',
    clientId: 'CLT-005',
    clientName: 'Fintech Solutions',
    employeeId: 'EMP-008',
    employeeName: 'Sarah Wilson',
    date: '2024-03-01',
    duration: 6.0,
    isBillable: true,
    billableRate: 180,
    notes: 'Migrating legacy user data to new encrypted schema.',
    status: 'Completed',
  },
  {
    id: 'TIME-004',
    projectId: 'INTERNAL-01',
    projectName: 'Internal Admin Refactor',
    taskId: 'TSK-INT-01',
    taskName: 'Internal Training',
    clientId: 'INTERNAL',
    clientName: 'Billing Software Inc',
    employeeId: 'EMP-005',
    employeeName: 'Jeel Uniya',
    date: '2024-02-28',
    duration: 2.0,
    isBillable: false,
    billableRate: 0,
    notes: 'Onboarding new junior developers for the Q2 project.',
    status: 'Completed',
  },
];

export const MOCK_TIMESHEETS: Timesheet[] = [
  {
    id: 'TS-2024-09',
    employeeId: 'EMP-005',
    employeeName: 'Jeel Uniya',
    startDate: '2024-02-26',
    endDate: '2024-03-03',
    totalHours: 42.5,
    billableHours: 38.0,
    status: 'Submitted',
    submittedAt: '2024-03-01T17:30:00Z',
  },
  {
    id: 'TS-2024-08',
    employeeId: 'EMP-005',
    employeeName: 'Jeel Uniya',
    startDate: '2024-02-19',
    endDate: '2024-02-25',
    totalHours: 40.0,
    billableHours: 35.5,
    status: 'Approved',
    submittedAt: '2024-02-23T16:00:00Z',
    approvedAt: '2024-02-24T09:00:00Z',
    approvedBy: 'Admin User',
  },
];

export const MOCK_PROJECT_STATS: ProjectTimeStats[] = [
  {
    projectId: 'PRJ-101',
    projectName: 'E-commerce Platform Redesign',
    budgetedHours: 500,
    actualHours: 345,
    billableHours: 310,
    costToDate: 45000,
    revenueToDate: 52000,
    utilization: 85,
    tasks: [
      { id: 'TSK-001', name: 'UI Components', hours: 120, status: 'Completed' },
      { id: 'TSK-002', name: 'API Integration', hours: 110, status: 'In Progress' },
    ],
  },
  {
    projectId: 'PRJ-102',
    projectName: 'Mobile App Backend',
    budgetedHours: 300,
    actualHours: 310, // Over budget
    billableHours: 290,
    costToDate: 55800,
    revenueToDate: 62000,
    utilization: 96,
    tasks: [
      { id: 'TSK-105', name: 'DB Schema', hours: 80, status: 'Completed' },
    ],
  },
];

export const MOCK_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'ATT-001',
    employeeId: 'EMP-005',
    date: '2024-03-01',
    clockIn: '09:05',
    clockOut: '18:15',
    breaks: [{ start: '13:00', end: '14:00', type: 'Lunch' }],
    totalWorkHours: 8.16,
    status: 'Present',
    shiftId: 'SHIFT-MORNING',
  },
];

export const MOCK_TIME_SUMMARY: TimeSummary = {
  totalHoursToday: 8.5,
  totalHoursWeek: 42.5,
  billableHoursWeek: 38.0,
  nonBillableHoursWeek: 4.5,
  overtimeHoursWeek: 2.5,
  productivityScore: 92,
  weeklyTrend: [
    { day: 'Mon', hours: 8.5, billable: 7.5 },
    { day: 'Tue', hours: 9.0, billable: 8.0 },
    { day: 'Wed', hours: 8.0, billable: 7.0 },
    { day: 'Thu', hours: 8.5, billable: 7.5 },
    { day: 'Fri', hours: 8.5, billable: 8.0 },
  ],
  projectDistribution: [
    { project: 'E-commerce Platform', hours: 25, color: '#6366f1' },
    { project: 'Mobile App Backend', hours: 12, color: '#10b981' },
    { project: 'Internal Admin', hours: 5.5, color: '#f59e0b' },
  ],
};
