import { Asset, AssetSummary, MaintenanceRecord, AssetTransferRecord } from '@/types/asset';

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'AST-001',
    name: 'MacBook Pro 16" (M3 Max)',
    category: 'IT Equipment',
    location: 'Corporate Office - Level 4',
    purchaseDate: '2024-01-15',
    purchaseCost: 3499,
    currentValue: 2850,
    depreciationMethod: 'Straight Line',
    status: 'Active',
    assignedTo: 'Jeel Uniya',
    serialNumber: 'MBP2024X991',
    department: 'Engineering',
    warrantyExpiry: '2025-01-15',
    insuranceExpiry: '2025-01-15',
    riskFactor: 'Low',
    utilization: 95,
  },
  {
    id: 'AST-002',
    name: 'Dell UltraSharp 32" 4K Monitor',
    category: 'IT Equipment',
    location: 'Corporate Office - Level 4',
    purchaseDate: '2023-11-20',
    purchaseCost: 899,
    currentValue: 720,
    depreciationMethod: 'Straight Line',
    status: 'Active',
    assignedTo: 'Jeel Uniya',
    serialNumber: 'DELL-US32-P11',
    department: 'Engineering',
    warrantyExpiry: '2026-11-20',
    riskFactor: 'Low',
    utilization: 100,
  },
  {
    id: 'AST-003',
    name: 'CNC Milling Machine - Model X',
    category: 'Machinery',
    location: 'Manufacturing Plant - Zone A',
    purchaseDate: '2022-05-10',
    purchaseCost: 45000,
    currentValue: 32000,
    depreciationMethod: 'Double Declining Balance',
    status: 'Maintenance',
    assignedTo: 'Robert Brown',
    serialNumber: 'CNC-MX-8822',
    department: 'Operations',
    lastMaintenanceDate: '2024-02-15',
    warrantyExpiry: '2025-05-10',
    riskFactor: 'Medium',
    utilization: 45,
  },
  {
    id: 'AST-004',
    name: 'Executive Desk - Walnut',
    category: 'Furniture',
    location: 'Corporate Office - Level 6',
    purchaseDate: '2023-03-05',
    purchaseCost: 1200,
    currentValue: 1050,
    depreciationMethod: 'Straight Line',
    status: 'Active',
    assignedTo: 'Sarah Wilson',
    department: 'Management',
    riskFactor: 'Low',
    utilization: 80,
  },
  {
    id: 'AST-005',
    name: 'Company Truck - Ford F-150',
    category: 'Vehicles',
    location: 'Logistics Hub',
    purchaseDate: '2021-08-12',
    purchaseCost: 55000,
    currentValue: 38500,
    depreciationMethod: 'Sum of Years Digits',
    status: 'In Repair',
    assignedTo: 'James Moore',
    serialNumber: 'FORD-F150-VIN921',
    department: 'Logistics',
    lastMaintenanceDate: '2024-02-28',
    insuranceExpiry: '2024-08-12',
    riskFactor: 'High',
    utilization: 10,
  },
  {
    id: 'AST-006',
    name: 'Server Rack UPS (Backup)',
    category: 'Infrastructure',
    location: 'Data Center - Rack 4',
    purchaseDate: '2023-01-20',
    purchaseCost: 4200,
    currentValue: 3400,
    depreciationMethod: 'Straight Line',
    status: 'Active',
    department: 'IT',
    riskFactor: 'Medium',
    utilization: 100,
  },
];

export const MOCK_ASSET_SUMMARY: AssetSummary = {
  totalAssets: 124,
  activeAssets: 102,
  maintenanceAssets: 15,
  totalValue: 845000,
  depreciatedValue: 125400,
  utilizationRate: 78.5,
  monthlyValueTrend: [
    { month: 'Sep', value: 780000 },
    { month: 'Oct', value: 795000 },
    { month: 'Nov', value: 810000 },
    { month: 'Dec', value: 835000 },
    { month: 'Jan', value: 840000 },
    { month: 'Feb', value: 845000 },
  ],
  categoryDistribution: [
    { category: 'IT Equipment', count: 45, value: 125000 },
    { category: 'Machinery', count: 12, value: 450000 },
    { category: 'Vehicles', count: 8, value: 220000 },
    { category: 'Furniture', count: 35, value: 42000 },
    { category: 'Infrastructure', count: 24, value: 8000 },
  ],
  maintenanceCosts: [
    { month: 'Sep', cost: 1200 },
    { month: 'Oct', cost: 4500 },
    { month: 'Nov', cost: 2800 },
    { month: 'Dec', cost: 1500 },
    { month: 'Jan', cost: 6200 },
    { month: 'Feb', cost: 3400 },
  ],
};

export const MOCK_MAINTENANCE_HISTORY: MaintenanceRecord[] = [
  {
    id: 'MNT-001',
    assetId: 'AST-003',
    date: '2024-02-15',
    type: 'Routine',
    description: 'Quarterly sensor calibration and lubrication of moving parts.',
    cost: 450,
    performer: 'Industrial Tech Solutions',
    status: 'Completed',
    nextServiceDate: '2024-05-15',
  },
  {
    id: 'MNT-002',
    assetId: 'AST-005',
    date: '2024-02-28',
    type: 'Repair',
    description: 'Brake pad replacement and engine diagnostic check.',
    cost: 850,
    performer: 'City Auto Center',
    status: 'Completed',
  },
  {
    id: 'MNT-003',
    assetId: 'AST-001',
    date: '2023-12-10',
    type: 'Upgrade',
    description: 'RAM upgrade from 32GB to 64GB and thermal paste replacement.',
    cost: 320,
    performer: 'Internal IT - David Smith',
    status: 'Completed',
  },
];

export const MOCK_ASSET_TRANSFERS: AssetTransferRecord[] = [
  {
    id: 'TRF-001',
    assetId: 'AST-001',
    date: '2024-01-20',
    fromLocation: 'Warehouse',
    toLocation: 'Corporate Office - Level 4',
    fromDepartment: 'Inventory',
    toDepartment: 'Engineering',
    transferBy: 'Inventory Manager',
  },
];
